@startuml global use case diagram
left to right direction

skinparam nodesep 20
skinparam ranksep 180

actor "User" as u



usecase  "Create project" as uc30
usecase  "Select data source" as uc31
usecase  "Select folder from server" as uc32
usecase  "Upload folder from machine" as uc33
usecase  "Select project members" as uc34


usecase  "Manage data " as uc40
usecase  "Scan data " as uc41
usecase  "Clear data " as uc42


usecase  "Manage geofile " as uc50
usecase  "Plot geofile " as uc55

usecase  "Map geodata" as uc60

usecase  "Manage project" as uc80


usecase  "Manage project details" as uc90




u -- uc30
uc30 ..> uc31
uc31 <|-- uc33
uc31 <|-- uc32
uc30 ..> uc34




u -- uc40


u -- uc50


u -- uc55


u -- uc60


u -- uc80


u -- uc90


@enduml


' EXTEND
' @startuml
' :Main Admin: as Admin
' (Use the application) as (Use)

' User <|-- Admin
' (Start) <|-- (Use)

' @enduml

' INCLUDES ARROW
' @startuml
' (Use case 1) <.. :user:
' (Use case 2) <- :user:
' @enduml