@startuml Project creation index
actor       User       as user
boundary    NavigationWidget    as b_widget
boundary    NativeFodlerSelector    as b_native_widget
boundary    CreateProjectForm    as b_project
boundary    Browser    as b_browser
control     FoldersNavigator     as c_folder
control     FileUploadHandler    as c_file_upload
  
mainframe **Select data source paths**

alt Select folder path form server
    loop
        user -> b_widget: selectDirectory
        b_widget -> c_folder:   getFolderContent(selectedDir)
        c_folder --> b_widget:  folderContent
        b_widget --> b_widget:  showFolderContent
    end
    alt confirm
        user -> b_widget: Click confirm
        b_widget --> b_project: Add to selected paths
        b_project --> b_project: Add to selected paths
    else decline
        user -> b_widget: Click discard
    end
else Upload folder from current local machine
    loop
        user -> b_native_widget: selectFolder
        b_native_widget --> b_native_widget: showFolderContent(newFolder)
    end
    user        ->  b_native_widget: Click upload
    b_browser   ->  b_browser: Asks upload confirmation
    user        ->  b_browser: Click confirm
    b_browser   ->  c_file_upload : uploadFiles(folderContent)
    c_file_upload --> b_project: uploadPath
    b_project --> b_project: Add to selected paths
    note left
        folder file content are looked up recursively
    end note
end
